# Generated by Django 4.2 on 2023-04-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0003_alter_profile_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='text1',
            field=models.TextField(default='Текст', verbose_name='Текст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='text2',
            field=models.TextField(default='Текст', verbose_name='Текст'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='external_id',
            field=models.PositiveIntegerField(verbose_name='Внешний ID пользователя'),
        ),
    ]
