# Generated by Django 4.2 on 2023-05-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0004_message_text1_message_text2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='text1',
        ),
        migrations.RemoveField(
            model_name='message',
            name='text2',
        ),
        migrations.AddField(
            model_name='message',
            name='lecturename',
            field=models.TextField(default='-1', verbose_name='-1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='texteng',
            field=models.TextField(default='cat', verbose_name='cat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='textrus',
            field=models.TextField(default='кошка', verbose_name='кошка'),
            preserve_default=False,
        ),
    ]
